### ISSUE TITLE
Difficulty?

### ISSUE THREAD

**Issue by 603598672** [tevador/equix#4]
I'm unsure how/if I can tweak the 'difficulty' of equix puzzles without affecting memory or verification the way I can with something like hashcash. I've read through your devlog and benchmark code and got some basic tests working, but I'm not very crypto-literate, so while it's probably obvious to those who are I'm not sure if this is a limitation of this type of puzzle or if I'm just missing some knob.

**Comment by tevador** [comment]
Adjustable difficulty can be achieved using a hashcash-like step. You can read the Tor proposal and take inspiration there.

https://github.com/torproject/torspec/blob/8961bb4d83fccb2b987f9899ca83aa430f84ab0c/proposals/327-pow-over-intro.txt#L310-L323

**Comment by 603598672** [comment]
Answers it completely, thank you so much!
